### ISSUE TITLE
Plugin fails to load with Leaflet 1.1.0

### ISSUE THREAD

**Issue by svvac** [bbecquet/Leaflet.RotatedMarker#13]
Yesterday's update breaks the loading phase of the plugin. Upon initialization, the line:

```javascript
var proto_onDrag = L.Handler.MarkerDrag.prototype._onDrag;
```
This call throws because `L.Handler.MarkerDrag` is `undefined`.

Reverting to `1.0.x` fixes the issue.

**Comment by bbecquet** [comment]
Thanks for reporting. This must be a side-effect of the new ES6-based build of Leaflet.
This part of my plug-in isn't very clean anyway, I'll have to find something else.

**Comment by bbecquet** [comment]
Ok, this way of doing was really dirty :) I've pushed a new release which does things properly and does not break with Leaflet 1.1.0, at least on my tests.
Can you please try it and close the issue if it solved things for you?

**Comment by bbecquet** [comment]
Closing it, I think it's solved with my tests and the 2 :+1: s above. Don't hesitate to re-open if it's still broken for you.
