### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by hogancr** [bbecquet/Leaflet.RotatedMarker#2]
I'm a little new at this, but I don't seem to find your project on bower even though you've got a bower.js. Did you not register it or something? How would I refer to your project to find it on bower? I'm using brunchJS as my build chain if it matters, and when I use 

"leaflet-rotatedmarker": "~0.1.0"

As a dependency in my bower.json I get the error ENOTFOUND Package leaflet-rotatedmarker not found. It also doesn't appear in the package search on bower.io
https://bower.io/search/

**Comment by bbecquet** [comment]
Hi :) ! (and sorry for the delay, I was in holidays during the last 10 days).

Actually this project doesn't have a `bower.json` file, so it's normal you didn't see it on the repository. Maybe you've confused it with my other project `PolylineDecorator` (the only one I put on Bower if IIRC), or something else?

In any case, I don't like putting my recent projects on bower, as it has mostly become obsolete. NPM/`package.json` is now the standard for JS packages, even for client-side projects, as builders will do the job of resolving dependencies and transforming what needs to be for front-end. As you are using `BrunchJS` (great choice!), it has perfect support of NPM and I think you should try to use my project as it.
Actually the Brunch doc advises against Bower when possible: http://brunch.io/docs/js-modules-npm.html#using-bower

If there is a better reason for the Bower support or if you need help, feel free to comment further :)
