### ISSUE TITLE
Rotate only a specific child element of divIcon

### ISSUE THREAD

**Issue by Yawarzy** [bbecquet/Leaflet.RotatedMarker#35]
Hi, I am using this library to rotate my custom marker. But I have a label for the marker, which also rotates with the marker. I wanted to rotate only my icon (which I add throught the L.divIcon). Is there a way for it ?

**Comment by matthewtboyle** [comment]
I have been dealing with this same issue. I ultimately ended up having the label rotate counter to the marker. this is an acceptable but not entirely desired solution. What did you come up with?
