### ISSUE TITLE
Conflict with https://github.com/stefanocudini/leaflet-search in Leaflet 1.0.0

### ISSUE THREAD

**Issue by tomchadwin** [bbecquet/Leaflet.RotatedMarker#6]
```javascript
leaflet.rotatedMarker.js:9
Uncaught TypeError: Cannot read property 'iconAnchor' of undefined
(anonymous function) @ leaflet.rotatedMarker.js:9
proto.callInitHooks @ leaflet.js:365
proto.callInitHooks @ leaflet.js:359
NewClass @ leaflet.js:314
onAdd @ leaflet-search.js:137
addTo @ leaflet.js:11610
addTo @ leaflet-search.js:160
addControl @ leaflet.js:11674
(anonymous function) @ index.html:121
```

See https://github.com/stefanocudini/leaflet-search/issues/139

**Comment by bbecquet** [comment]
Hi.
I've put a diagnostic of the bug [in the leaflet-search issue](https://github.com/stefanocudini/leaflet-search/issues/139#issuecomment-250541917) and I published a new version of `leaflet-rotatedmarker` which should fix the problem.
Keep me informed :)

**Comment by tomchadwin** [comment]
Confirmed fixed - thanks so much! 'll leave the issue open on @stefanocudini's repo, so he can look at your suggestion.

**Comment by stefanocudini** [comment]
fine!
