### ISSUE TITLE
Draggable Markers reset to 0 degrees on drag.

### ISSUE THREAD

**Issue by Andrew-SK** [bbecquet/Leaflet.RotatedMarker#9]
As soon as dragging begins the icon is rendered without the set rotationAngle.

Edit: I quickly created this [jsfiddle](https://jsfiddle.net/crty7d1c/) to demonstrate

**Comment by Andrew-SK** [comment]
It looks like this is due to the MarkerDrag._onDrag function setting the marker._latlng property directly.

```
	_onDrag: function (e) {
		var marker = this._marker,
		    shadow = marker._shadow,
		    iconPos = L.DomUtil.getPosition(marker._icon),
		    latlng = marker._map.layerPointToLatLng(iconPos);

		// update shadow position
		if (shadow) {
			L.DomUtil.setPosition(shadow, iconPos);
		}

		marker._latlng = latlng;
		e.latlng = latlng;
		e.oldLatLng = this._oldLatLng;

		// @event drag: Event
		// Fired repeatedly while the user drags the marker.
		marker
		    .fire('move', e)
		    .fire('drag', e);
	},
```

**Comment by m314** [comment]
+1; I am also observing this in my code.

**Comment by bbecquet** [comment]
I'm closing the bug, as I've merged the fix and published the new version. Thanks a lot again @Andrew-SK!
